# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-20 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexgoodsbanner',
            name='image',
            field=models.ImageField(upload_to='banneregisterr', verbose_name='图片'),
        ),
    ]
